"""Minimal FastAPI entry-point for a containerised AI agent.

This file is intended as part of the `agent-template` cookie-cutter.  When a new
agent is generated, users will typically customise:
  • the Pydantic request/response schemas
  • the implementation inside `invoke()`

The runtime contract expected by the Agent Control Plane is:
  POST /invoke    – main inference/action endpoint
  GET  /health    – liveness probe
  GET  /metadata  – YAML metadata from `agent.yaml`
"""

from datetime import datetime
from typing import Any, Dict, List
import logging
from dotenv import load_dotenv
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langgraph.graph import StateGraph, END

# AgentSystems model routing - no fallbacks to force proper configuration
from agentsystems_toolkit import get_model

# Langfuse tracing handler (framework-agnostic)
from langfuse.langchain import CallbackHandler

# Progress reporting helper from agentsystems toolkit
try:
    from agentsystems_toolkit import progress_tracker as pt  # type: ignore
except ImportError:  # Graceful degradation if progress tracking not available
    pt = None  # noqa: N818

import pathlib

import yaml
import time
from fastapi import FastAPI, Request
from pydantic import BaseModel

# ── Load static metadata once at startup ──────────────────────────────────────
meta_path = pathlib.Path(__file__).with_name("agent.yaml")
if not meta_path.exists():
    raise FileNotFoundError(
        "agent.yaml not found next to main.py – required by template"
    )

meta: Dict[str, Any] = yaml.safe_load(meta_path.read_text())
NAME: str = meta.get("name", "UnnamedAgent")
VERSION: str = meta.get("version", "0.0.0")

app = FastAPI(title=NAME, version=VERSION)


# ── Pydantic Schemas – replace with your own ─────────────────────────────────
class InvokeRequest(BaseModel):
    date: str | None = None  # e.g. "April 1" - optional if provided via file upload


class InvokeResponse(BaseModel):
    thread_id: str  # UUID generated by gateway and echoed back
    date: str
    events: List[str]
    story: str
    timestamp: datetime


# ── Routes – minimal contract ────────────────────────────────────────────────
# ── Build LangGraph pipeline once at startup ────────────────────────────────
load_dotenv()

# Get configured model - will fail if not properly configured
# The toolkit automatically routes to the correct provider based on platform configuration
_llm = get_model("claude-sonnet-4", "langchain", temperature=0)
# _llm = get_model("gpt-5-nano", "langchain", temperature=0)
# _llm = get_model("llama3.3:70b", "langchain", temperature=0)
# _llm = get_model("gemma3:4b", "langchain", temperature=0)

logging.info("Using model routing via agentsystems-toolkit")

# ── Artifacts volume convenience constant ────────────────────────────
# Thread-centric artifacts - no agent-specific directory needed
ARTIFACTS_ROOT = pathlib.Path("/artifacts")

# Prompt for historical events (expects VALID JSON)
_events_prompt = PromptTemplate(
    template=(
        """
        You are a helpful AI that MUST return VALID JSON ONLY. No markdown.
        Return exactly 3 historical events that occurred on this month/day: {date}

        Expected format:\n{{\n  \"events\": [ \"Event #1\", \"Event #2\", \"Event #3\" ] }}

        Ensure that the selected historical events are family friendly and appropriate to be thoroughly discussed with people of all ages and backgrounds.
        """
    ),
    input_variables=["date"],
)

# _llm is now defined above in the model routing section
_parser = JsonOutputParser()
_chain_events = _events_prompt | _llm | _parser

_story_prompt = PromptTemplate(
    template="""
    Compose a concise, engaging narrative (max 120 words) weaving these historical events together on {date}:
    {events}
    Ensure that all content is family friendly and appropriate for people of all ages and backgrounds.
    """,
    input_variables=["date", "events"],
)
_chain_story = _story_prompt | _llm

# Langfuse callback handler – initialise once at startup
langfuse_handler = CallbackHandler()


class _SGState(dict):
    date: str
    historical_events: List[str]
    story: str


graph = StateGraph(_SGState)


def delay_node(state: _SGState) -> _SGState:
    """Small 2-second delay split into 2 visible 1-second chunks."""
    if not (pt and _thread_id):
        time.sleep(2)
        return state

    for i in range(1, 3):
        step_id = f"delay_{i}"
        pct = 30 + i * 25  # 55, 80
        pt.update(current=step_id, state={step_id: "running"}, percent=pct)
        time.sleep(1)
        pt.update(state={step_id: "completed"}, percent=pct)
    return state


def get_historical_events_node(state: _SGState) -> _SGState:
    # Mark the first step as running
    if pt and _thread_id:
        pt.update(current="events", state={"events": "running"}, percent=10)

    result = _chain_events.invoke({"date": state["date"]})
    state["historical_events"] = result.get("events", [])
    if pt and _thread_id:
        pt.update(state={"events": "completed", "delay": "queued"}, percent=30)
    return state


def story_node(state: _SGState) -> _SGState:
    if pt and _thread_id:
        # events finished, story running
        pt.update(state={"delay": "completed", "story_node": "running"}, percent=80)

    story_result = _chain_story.invoke(
        {"date": state["date"], "events": state["historical_events"]}
    )
    # LangChain may return an AIMessage; extract its content if present
    if hasattr(story_result, "content"):
        story_text = story_result.content
    else:
        story_text = str(story_result)
    state["story"] = story_text
    if pt and _thread_id:
        pt.update(state={"story_node": "completed"}, percent=100, message="completed")
    return state


graph.add_node("events", get_historical_events_node)
graph.add_node("delay", delay_node)
graph.add_node("story_node", story_node)

# Flow: events -> delay -> story_node
graph.add_edge("events", "delay")
graph.add_edge("delay", "story_node")
graph.add_edge("story_node", END)
graph.set_entry_point("events")
_pipeline = graph.compile().with_config({"callbacks": [langfuse_handler]})


@app.post("/invoke", response_model=InvokeResponse, tags=["Agent Ops"])
async def invoke(request: Request, req: InvokeRequest) -> InvokeResponse:  # noqa: D401
    """Return three events for the given date and a short narrative."""
    thread_id = request.headers.get("X-Thread-Id", "")
    global _thread_id
    _thread_id = thread_id  # expose to node functions

    # --- Progress plan declaration ---
    if pt and thread_id:
        plan = [
            {"id": "events", "label": "Fetch Historical Events"},
            *[{"id": f"delay_{i}", "label": f"Wait {i}s"} for i in range(1, 3)],
            {"id": "story_node", "label": "Compose Story"},
        ]
        pt.init(
            thread_id,
            plan=plan,
            auth_header=request.headers.get("Authorization"),
        )
    # Resolve input date – prefer date.txt file in artifacts volume
    # List contents of the thread-centric input directory for easier debugging
    in_dir = ARTIFACTS_ROOT / thread_id / "in"
    if in_dir.exists():
        logging.info(
            f"artifact_input_dir_contents: {[p.name for p in in_dir.iterdir()]}"
        )
    else:
        logging.warning(f"artifact_input_dir_missing: {str(in_dir)}")

    # Thread-centric path: /artifacts/{thread_id}/in/date.txt
    in_file = in_dir / "date.txt"
    if in_file.exists():
        date_value = in_file.read_text().strip()
    elif req.date:
        date_value = req.date
    else:
        # Fallback if no date provided in JSON or file
        date_value = "December 25"

    initial_state = {
        "date": date_value,
        "historical_events": [],
        "thread_id": thread_id,
    }
    final_state: _SGState = _pipeline.invoke(
        initial_state,
        config={
            "metadata": {"langfuse_session_id": thread_id} if thread_id else {},
        },
    )  # type: ignore[arg-type]
    # Persist story artifact to artifacts volume (thread-centric path)
    out_dir = ARTIFACTS_ROOT / thread_id / "out"
    # Create the 'out' subdirectory - thread base directory created by gateway
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "story.txt").write_text(str(final_state.get("story", "")))

    # Attach control-plane thread_id to Langfuse trace as session_id

    return InvokeResponse(
        thread_id=thread_id,
        date=date_value,
        events=final_state["historical_events"],
        story=str(final_state.get("story", "")),
        timestamp=datetime.utcnow(),
    )


@app.get("/health", tags=["Agent Ops"])
async def health() -> Dict[str, str]:
    return {"status": "ok", "version": VERSION}


@app.get("/metadata", tags=["Agent Ops"])
async def metadata() -> Dict[str, Any]:
    return meta
